# Generated by Django 5.2.8 on 2025-11-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tokens_used',
            field=models.IntegerField(default=0, help_text='Number of tokens used for this generation'),
        ),
    ]
